CREATE DATABASE IF NOT EXISTS barcode_generator
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE barcode_generator;

CREATE TABLE IF NOT EXISTS barcode_batches (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  format VARCHAR(32) NOT NULL DEFAULT 'CODE128',
  code_count INT UNSIGNED NOT NULL DEFAULT 0,
  codes_json TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
